//DATABASE
var database = Array();
database.push(["C043", "ISCTE", ""]);
database.push(["C032", "ISCTE", ""]);
database.push(["C018", "ISCTE", ""]);
database.push(["C006", "ISCTE", ""]);
database.push(["C019", "ISCTE", ""]);
database.push(["C048", "ISCTE", ""]);
database.push(["C098", "ISCTE", ""]);
database.push(["C030", "ISCTE", ""]);
database.push(["C042", "ISCTE", ""]);
database.push(["C060", "ISCTE", ""]);
database.push(["C082", "ISCTE", ""]);
database.push(["C108", "ISCTE", ""]);
//fablab
database.push(["C010", "FabLab ", ""]);
database.push(["C035", "FabLab ", ""]);
database.push(["C117", "FabLab ", ""]);
database.push(["C061", "FabLab ", ""]);
database.push(["C096", "FabLab ", ""]);
database.push(["C112", "FabLab ", ""]);
database.push(["C024", "FabLab ", ""]);
database.push(["C041", "FabLab ", ""]);
database.push(["C079", "FabLab ", ""]);
database.push(["C068", "FabLab ", ""]);
database.push(["V017", "Almeida Guerra ", ""]);
database.push(["C037", "André Campino", ""]);
database.push(["A042", "Xiou Wen ", ""]);
database.push(["A037", "Zhou Qingjia ", ""]);
database.push(["A029", " ", ""]);
database.push(["A021", "Di Zhao ", ""]);
database.push(["A013", "Shaohuang Ma ", ""]);
database.push(["A006", "Tongyan Wang ", ""]);
database.push(["A004", "Lihong Gu ", ""]);
database.push(["A052", "Hui He", ""]);
database.push(["C065", "Daniel Nogueira ", ""]);
database.push(["C029", "Sara Eloy ", ""]);
database.push(["C038", "Pedro Carvalho ", ""]);
database.push(["L039", "João Batista ", ""]);
database.push(["C009", "Olinda Gama ", ""]);
database.push(["C128", "Paula Rodrigues ", ""]);
database.push(["C069", "Ana Costa ", ""]);
database.push(["C130", "Diana Costa ", ""]);
database.push(["L013", "Maria João Simas", ""]);
database.push(["C062", "João Pinote ", ""]);
database.push(["L005", "Luis Meneses", ""]);
database.push(["A084", "João Peniche Rosa", ""]);
database.push(["A116", "Braulio Alturas", ""]);
database.push(["A111", " ", ""]);
database.push(["C002", "Maria Glória Lopes ", ""]);
database.push(["C011", "Amigo secreto da Audax ", ""]);
database.push(["A008", "Luciano Leal ", ""]);
database.push(["C013", "Ana Madeira ", ""]);
database.push(["C014", "Ana Madeira ", ""]);
database.push(["C036", "Susana Trigo Cordeiro ", ""]);
database.push(["C055", "Carlos Glórias Ferreira ", ""]);
database.push(["C001", "Margarida Garrido ", ""]);
database.push(["V013", "Mazars e Associados ", ""]);
database.push(["C059", "Manuela Farrobilha ", ""]);
database.push(["C056", "Ana Siemaes ", ""]);

database.push(["A001", "Adelino Gomes", ""]);
database.push(["A002","AIESEC", ""]);
database.push(["A003","Andreia Miguel", ""]);
database.push(["A004","Marina Ventura", ""]);
database.push(["A006","José Paulo Esperança", ""]);
database.push(["A007","querty", ""]);
database.push(["A008","Luciano Leal 1981", ""]);
database.push(["A010","Jorge Bento; Gonçalo Silva; Finanças 1999…", ""]);
database.push(["A011","Shamil Indrakumar", ""]);
database.push(["A012","João Paulo Cavaco", ""]);
database.push(["A014","Maria Augusta Maia", ""]);
database.push(["A015","Alexandra Paio", ""]);
database.push(["A016","Margarida Patrocínio", ""]);
database.push(["A017","Pedro Nunes", ""]);
database.push(["A018","Diogo Beja ", ""]);
database.push(["A019",":-)", ""]);
database.push(["A020","Carlos Ambrósio", ""]);
database.push(["A024","Linda Almeida", ""]);
database.push(["A025","Sofia Marques", ""]);
database.push(["A026","Conceição Carrapeta", ""]);
database.push(["A027","Teresa Amorim OGE 1982", ""]);
database.push(["A028","Carlos Megre Amaral OGE 1982", ""]);
database.push(["A030","Pedro Dionísio", ""]);
database.push(["A031","Luís Alves", ""]);
database.push(["A032","José Rainho Coelho", ""]);
database.push(["A033","<3 Amo-te ISCTE - Dulce Mota 1980", ""]);
database.push(["A034","Mª. José Roque; 1980 Gestão", ""]);
database.push(["A036","F. Ramos", ""]);
database.push(["A040","Teresa Lopes e Paula Marina", ""]);
database.push(["A045","MCH", ""]);
database.push(["A047","Mª da Glória Morão Lopes", ""]);
database.push(["A049","Aurélia Dinis e Isidro Duarte", ""]);
database.push(["A068","Ana Simaens", ""]);
database.push(["A070","Cecília Aguiar", ""]);
database.push(["A071","1993-1998; CG. CV. MG. RG. PL. PV. RA. SA. RB. SL.", ""]);
database.push(["A073","José Vieira; Tudo Bem Pelo Conhecimento", ""]);
database.push(["A075","Pedro Sebastião", ""]);
database.push(["A076","Teresa Machado Graça 1980", ""]);
database.push(["A078","J. C. Alves; L. Mota; Madaleno; T.Marta", ""]);
database.push(["A082","A. F. Costa", ""]);
database.push(["A084","João Peniche Rosa", ""]);
database.push(["A085","Mário Nunes; Armando Henriques; Ourém; OEG; 14-12-12", ""]);
database.push(["A086","Cristina Rosa e Luís Peixoto", ""]);
database.push(["A087","Filomena Oliveira; Pedro Lameira; João Teixeira; OGE 1993/98", ""]);
database.push(["A090","Rita Silva e Pedro Félix", ""]);
database.push(["A091","Luís Rocha e Rita Duarte 14-12-12", ""]);
database.push(["A092","GGC ISCTE-IUL", ""]);
database.push(["A096","Paulo Nascimento Simões", ""]);
database.push(["A097","Carla Cardoso", ""]);
database.push(["A100","Gonçalo Amorim", ""]);
database.push(["A101","Vitor Monsanto", ""]);
database.push(["A102"," ", ""]);
database.push(["A105","Logotipo", ""]);
database.push(["A107","Anas e Pedros Souto", ""]);
database.push(["A108","Teresa Seabra", ""]);
database.push(["A111","Ana Paula Alturas", ""]);
database.push(["A116","Braúlio Alturas", ""]);
database.push(["A118","Ana Isabel Cordeiro Monteiro; José João Monteiro; Mª. do Rosário Vieira; Paulo Courela", ""]);
database.push(["A119","Carlos Glórias Ferreira", ""]);
database.push(["A120","João S. Batista", ""]);
database.push(["A121","Demi Perdigão - Rio de Janeiro", ""]);
database.push(["C001","Margarida Garrido", ""]);
database.push(["C002","João Pinote", ""]);
database.push(["C005","José Francisco de Almeida", ""]);
database.push(["C009","Olinda Gama", ""]);
database.push(["C011","Amigo Secreto - Audax", ""]);
database.push(["C012","Luís Solá", ""]);
database.push(["C013","Rui Neves Madeira", ""]);
database.push(["C014","Ana Neves Madeira", ""]);
database.push(["C015","Paula Lemos", ""]);
database.push(["C021","Cristina Quintanilha; Mendonça Santos 1977-1982", ""]);
database.push(["C022","Nuno Teixeira Santos", ""]);
database.push(["C023","Vensol", ""]);
database.push(["C026","Marc Renaud", ""]);
database.push(["C027","Teresa Patrício", ""]);
database.push(["C029","Sara Eloy", ""]);
database.push(["C031","Curso 1973/1978 Economia e Gestão", ""]);
database.push(["C034","Mafalda Garcês e Carlos Monteiro", ""]);
database.push(["C036","Susana Tiago Cordeiro", ""]);
database.push(["C037","The MUP Manifesto", ""]);
database.push(["C038","Pedro Carvalho", ""]);
database.push(["C039","IGE-PL; Tinoco Falé; Simões Bernardo", ""]);
database.push(["C040","Hugo Nogueira", ""]);
database.push(["C044","Maria das Dores Guerreiro", ""]);
database.push(["C045","Bigóstolos", ""]);
database.push(["C046","Francisco Cercas", ""]);
database.push(["C047","Logotipo", ""]);
database.push(["C049","1979-1984; António Rato; Fernando Soares; João Correia; José Rodrigues; Vitor Santos ", ""]);
database.push(["C050","Ana Rodrigues", ""]);
database.push(["C051","Kátia Leal 2011", ""]);
database.push(["C053","João Baltazar Arquitetos", ""]);
database.push(["C054","Luís Neves; Carla Bray", ""]);
database.push(["C056","Antónia Mota", ""]);
database.push(["C057","Mª João Oliveira", ""]);
database.push(["C058","Donalda Martinho", ""]);
database.push(["C059","Manuela Farrobilha", ""]);
database.push(["C062","Otília Santos", ""]);
database.push(["C064","Odete Pendão", ""]);
database.push(["C065","David Nogueira", ""]);
database.push(["C069","Ana Costa", ""]);
database.push(["C072","Fernando de Figueiredo", ""]);
database.push(["C078","Tiago Lalanda e Pedro Feliciano; Gestão 05-08", ""]);
database.push(["C082","CEAAD 2012", ""]);
database.push(["C084","Margarida Perestrelo", ""]);
database.push(["C085","Sandra Galé", ""]);
database.push(["C086","Armindo do Espírito Santo", ""]);
database.push(["C091","Pedro Pinto", ""]);
database.push(["C092","Diogo Andrade Alves", ""]);
database.push(["C093","Pedro Lourenço", ""]);
database.push(["C094","José Constantino Leal Ferreira", ""]);
database.push(["C095","José Manuel Botelho", ""]);
database.push(["C101","António C. Lopes", ""]);
database.push(["C102","IGE e OGE 90-95", ""]);
database.push(["C103","J. Maria", ""]);
database.push(["C104","Sandro Mendonça", ""]);
database.push(["C105","Ana Maria Nabeto; ISCTE - Curso Gestão 1986/1987", ""]);
database.push(["C114","Ana Xavier", ""]);
database.push(["C115","Alberto Cruz", ""]);
database.push(["C116","Álvaro Esteves - Media Alta - Comunicação", ""]);
database.push(["C121","Sibila Marques; Claúdia Andrade", ""]);
database.push(["C122","Bruno N. Jivan", ""]);
database.push(["C124","Gonçalo Norte ", ""]);
database.push(["C125","Paula Borges", ""]);
database.push(["C126","Nuno Reis; Miguel Ferrão; Gestão", ""]);
database.push(["C128","Paula Rodrigues", ""]);
database.push(["C130","Diana Costa", ""]);
database.push(["C131","Mª. Fátima", ""]);
database.push(["C133","Maria da Graça", ""]);
database.push(["C134","Margarida Mata 1992", ""]);
database.push(["C135","Patrícia Matos; OEG 92-97", ""]);
database.push(["C136","Carla Garcez", ""]);
database.push(["C137","Pedro Lisboa OGE 93-98", ""]);
database.push(["C138","Sandra Ávila OGE 93-98", ""]);
database.push(["L001","Isabel Salavisa Lança", ""]);
database.push(["L002","Fernando Neves de Almeida", ""]);
database.push(["L004","Silver Steam", ""]);
database.push(["L005","Luís Cardoso Meneses", ""]);
database.push(["L010","F.L.M.", ""]);
database.push(["L011","Filomena Almeida", ""]);
database.push(["L013","Maria João Simas", ""]);
database.push(["L014"," ", ""]);
database.push(["L015"," ", ""]);
database.push(["L016","José Manuel Paquete de Oliveira", ""]);
database.push(["L026","José Valentim Marques", ""]);
database.push(["L028","José Serrano Gordo 1978", ""]);
database.push(["L031","J.F.B", ""]);
database.push(["L036"," ", ""]);
database.push(["L039","João Dias", ""]);
database.push(["L045","Cristina Pegado e José Gouveia, 1992", ""]);
database.push(["L051","Mª. José Gaspar", ""]);
database.push(["L058","Ricardo Branco; Pedro Jesus; Nuno Cardoso; Miguel Braz", ""]);
database.push(["L059","Eduardo Martins e Nelson Quico", ""]);
database.push(["L060","Sérgio Cruz", ""]);
database.push(["L062","Montepio ", ""]);
database.push(["R004","Nuno Amado ISCTE 1980", ""]);
database.push(["R011","Aurora Baptista OGE 1983", ""]);
database.push(["V003","António Manuel S. Melo Rodrigues; 1980 - Gestão", ""]);
database.push(["V013","Logotipo", ""]);
database.push(["V017","José Almeida Guerra", ""]);

// últimas
database.push(["A005"," ", ""]);
database.push(["V012"," ", ""]);
database.push(["A112"," ", ""]);


database.push(["A112"," ", ""]);